// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBdlZ6erHpLWg4nWZcUiG3cJPTBPROTRo',
    appId: '1:1070677438895:web:bd77cefd275eec0958bf5a',
    messagingSenderId: '1070677438895',
    projectId: 'login-d3061',
    authDomain: 'login-d3061.firebaseapp.com',
    storageBucket: 'login-d3061.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1n0OVoQ6_kf4LOvszSDijyTl2WcJ7l1A',
    appId: '1:1070677438895:android:9e14ec8bcee9e59858bf5a',
    messagingSenderId: '1070677438895',
    projectId: 'login-d3061',
    storageBucket: 'login-d3061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNel6aO2_bGip7ZhvfY7AXiF05iH-MWU',
    appId: '1:1070677438895:ios:3486d694275d7c9458bf5a',
    messagingSenderId: '1070677438895',
    projectId: 'login-d3061',
    storageBucket: 'login-d3061.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNel6aO2_bGip7ZhvfY7AXiF05iH-MWU',
    appId: '1:1070677438895:ios:3d3dffe3fc53e5cb58bf5a',
    messagingSenderId: '1070677438895',
    projectId: 'login-d3061',
    storageBucket: 'login-d3061.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
